### ISSUE TITLE
link to classic is wrong

### ISSUE THREAD

**Issue by shrop** [meteor-charlotte/website#1]
@tbjers can you update the link to classic. Should be `https://knowclassic.com`

I tried to do a pull request, but I don't see where you committed `settings.json`.

Thanks!

**Comment by tbjers** [comment]
Settings.json should never be committed since it contains my API credentials for Meetup.com. I'll go ahead and change it.

**Comment by shrop** [comment]
Ahh makes sense. Thanks man!
